### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by The-Futurist** [PositiveTechnologies/AspxParser#3]
Hi,

May I ask what was the motivation for this project? I'm considering analyzing a huge legacy app that contains many hundreds of .aspx pages and so on and this parser might prove helpful.

Did you create it for that kind of problem or was it motivated bt academic curiosity?

Thx

**Comment by alexxn** [comment]
Hey,
As a security company we have to do a lot of parsing in different kinds of web applications. For some period we've been using Mono aspx parser in our internal projects. Unfortunately it was not sufficient for all our needs. So we decided to fork, fix some problems and tailor it a bit for ourselves.

If you feel it might be helpful, you should give it a try.

**Comment by The-Futurist** [comment]
@alexxn Thanks for explaining, I am going to fork your repo and play with it, might be very helpful.

**Comment by someone-with-default-username** [comment]
Hello, @Korporal! This project is only a parsing solution, not a typing one. Interpretation logic of ASP directives, control name binding and other stuff is not provided here. But this parser is built on top of original ASP.NET regular expressions and its behavior is quite close to TemplateParser from System.Web.dll.
